# Generated by Django 3.2.5 on 2022-08-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
